apiVersion: v1
kind: Service
metadata:
  name: kubernate-deploy-service
spec:
  type: LoadBalancer   # agar AWS/GCP pe ho to external IP milega, local minikube pe NodePort use karo
  selector:
    app: kubernate-deploy
  ports:
    - protocol: TCP
      port: 80         # Service external port
      targetPort: 8080 # Pod ke andar ka port
